### PR TITLE
[Consensus] Fix compilation with OpenSSL 1.1

### LINKED ISSUE #149: Latest OpenSSL 1.1.0e incorrectly detected as LibreSSL during build
### Describe the issue

After updating to OpenSSL 1.1.0e I can no longer build. `configure` fails with:

    configure: error: Detected LibreSSL: This is NOT supported, and may break consensus compatibility!

I don't have LibreSSL anywhere on my system though. I tried `configure --with-libressl` which runs successfully but then `make` fails:

````
Making all in src
make[1]: Entering directory '/mnt/tank/projects/PIVX/src'
make[2]: Entering directory '/mnt/tank/projects/PIVX/src'
  CXX      libbitcoinconsensus_la-allocators.lo
  CXX      primitives/libbitcoinconsensus_la-transaction.lo
  CXX      crypto/libbitcoinconsensus_la-hmac_sha512.lo
  CXX      crypto/libbitcoinconsensus_la-scrypt.lo
  CXX      crypto/libbitcoinconsensus_la-sha1.lo
  CXX      crypto/libbitcoinconsensus_la-sha256.lo
  CXX      crypto/libbitcoinconsensus_la-sha512.lo
  CXX      crypto/libbitcoinconsensus_la-ripemd160.lo
  CXX      libbitcoinconsensus_la-eccryptoverify.lo
  CXX      libbitcoinconsensus_la-ecwrapper.lo
ecwrapper.cpp: In function ‘int {anonymous}::ECDSA_SIG_recover_key_GFp(EC_KEY*, ECDSA_SIG*, const unsigned char*, int, int, int)’:
ecwrapper.cpp:62:28: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_add(x, x, ecsig->r)) {
                            ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1044:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:118:34: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_inverse(rr, ecsig->r, order, ctx)) {
                                  ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1044:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:123:31: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     if (!BN_mod_mul(sor, ecsig->s, rr, order, ctx)) {
                               ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1044:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp: In member function ‘bool CECKey::Recover(const uint256&, const unsigned char*, int)’:
ecwrapper.cpp:221:31: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&p64[0], 32, sig->r);
                               ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1044:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
ecwrapper.cpp:222:32: error: invalid use of incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
     BN_bin2bn(&p64[32], 32, sig->s);
                                ^~
In file included from ecwrapper.h:11:0,
                 from ecwrapper.cpp:5:
/usr/include/openssl/ec.h:1044:16: note: forward declaration of ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
 typedef struct ECDSA_SIG_st ECDSA_SIG;
                ^~~~~~~~~~~~
make[2]: *** [Makefile:6085: libbitcoinconsensus_la-ecwrapper.lo] Error 1
make[2]: Leaving directory '/mnt/tank/projects/PIVX/src'
make[1]: *** [Makefile:6949: all-recursive] Error 1
make[1]: Leaving directory '/mnt/tank/projects/PIVX/src'
make: *** [Makefile:592: all-recursive] Error 1
````

### What version of PIVX Core are you using?
Latest master, commit id 6b5cf7f8b

### Machine specs:
- OS: Arch Linux

### Any extra information that might be useful in the debugging process.
[config.log here](http://paste2.org/NXnGBIGU)

### PR DESCRIPTION
**Pull request by Warrows**
What prompted me to address the situation is related to issue #149 
Let's give a bit of context:
In bitcoin, openssl was used in consensus critical code. Following the infamous heartbleed vulnerability discovered in openssl code, libressl was created as a fork to refactor and improve ssl code. To this day, libressl is used as default instead of openssl in the os openBSD. As far as crypto are concerned: the openssl hotfix was integrated into bitcoin promptly. The change in consensus code triggered a fork. bip 66 was then decided, removing openssl code from consensus critical area and using custom implementation by core team instead. This bip was backported in dash commit 3d004ab which we inherited. So good so far. 
The thing is, before this bip a limitation was put into the autoconf to avoid compiling consensus critical code with the new lib libressl. We directly inherited this limitation from bitcoin core 0.10. It was removed from bitcoin core in commit a3874c7. Too late for us. Since then, anyone wanting to compile PIVX with libressl will get the warning as seen in #149. And this has never been removed. But this warning is not cleanly looking for libressl, it is using a workaround, testing the absence of a specific function existing in openssl 1.0 but removed in both libressl and openssl 1.1 prompting you to get a libressl warning if you are using openssl 1.1. The simple workaround would be to altogether remove the warning, as done by bitcoin.
But the thing which leaves me wondering in this situation is that when implementing libzerocoin, we came to depend on openssl again. Depend so much that we can't compile with openssl 1.1. Even by ignoring the warning thanks to the --with-libressl argument. This pull request aim to fix this compilation problem. I am not fully aware of the internal workings of the zerocoin implementation but surely, since it's burning and creating coins, it is influencing consensus. 

My advice would be: after merging this, either try to totally remove openssl dependency from any consensus critical code (especially related to zerocoin). If not possible, and anyway, as a short term fix: change the alert message and argument when compiling as to include openssl 1.1 beside libressl as potentially consensus breaking. This would allow to quickly close issue #149 

About testing: I compiled and ran unit tests on debian  with both openssl 1.0 and 1.1. I did not test libressl and I'd prefer if someone is able to try it on openbsd. I also minted and spent some zPIV on testnet without problem.

### CODE REVIEW

**Comment by presstab** [comment]
Hmm interesting.

@rejectedpromise please take a look at this PR, you have been dealing with the crypto side of the wallet recently, see if anything jumps out at you.

**Comment by rejectedpromise** [comment]
* added to my todo list

**Comment by rejectedpromise** [comment]
Changes to CBigNum scare me because of the heavy zPIV dependency on it. However, I do agree with moving towards removing dependencies on openssl, as bitcoin and others have done. 

utACK, hope to pull and test this weekend, but have a long todo list ;)

**Comment by Fuzzbawls** [comment]
While moving away from OpenSSL may be a good long-term goal, it certainly resides out of the scope of this PR.

That said, I think this PR would need to actually allow compiling against OpenSSL 1.1 without the use of `--with-libressl` argument as you've noted that it has become an inappropriate check. I don't think we actually want to support libressl, so changes to the check in the build system would be necessary.

**Comment by Warrows** [comment]
@Fuzzbawls We can agree `--with-libressl` is conceptually not the appropriate argument to compile with openssl 1.1. However I am not sure we want to support ossl1.1 any more than lssl. Bitcoin did not when their consensus was depending on it. Given the dependency for zPIV I think we need an argument for both lssl and ossl1.1. 
And I am not (yet) aware of a way to distinguish them efficiently in the configure process. Maybe I should just change argument name and warning texts to include both for now?

**Comment by Fuzzbawls** [comment]
I will try to do some more testing with this on a system that has OpenSSL 1.1 native (AFAIK Ubuntu 14.04 fully updated does this). I agree that we probably don't want to encourage OpenSSL 1.1 any more than LibreSSL, but if this PR is intended to provide OpenSSL 1.1 compatibility, then the build system will absolutely need to recognize that, if even for the short term.

**Comment by Warrows** [comment]
@Fuzzbawls Done and rebased. It's now simply stating "unsupported ssl version" instead of "libressl" when you compile with something else than OpenSSL 1.0.

**Comment by Fuzzbawls** [comment]
from a build-system perspective, the recent change is good. Would still like feedback from @rejectedpromise regarding the changes to bignum and crypter when forcing a compile against openssl 1.1

**Comment by tofutim** [comment]
I vote for this PR

**Comment by Mrs-X** [comment]
@rejectedpromise Any news on this?

**Comment by Warrows** [comment]
@rejectedpromise I found the problem and fixed it. It was a bad initialization of context in payment request plus.

**Comment by rejectedpromise** [comment]
Sweet!
I will try to test again either tonight or tomorrow 👍

**Comment by rejectedpromise** [comment]
Regular build and test build now passing

**Comment by Warrows** [comment]
So @presstab, @Mrs-X, @Fuzzbawls, are we waiting for more reviews or is it mergeable in your view ?

**Comment by Fuzzbawls** [comment]
@Warrows getting a compile-time error with this when using OpenSSL 1.1.0g

```make
qt/paymentrequestplus.cpp: In member function ‘bool PaymentRequestPlus::getMerchant(X509_STORE*, QString&) const’:
qt/paymentrequestplus.cpp:161:20: error: aggregate ‘EVP_MD_CTX _ctx’ has incomplete type and cannot be defined
         EVP_MD_CTX _ctx;
                    ^~~~
Makefile:5606: recipe for target 'qt/qt_libbitcoinqt_a-paymentrequestplus.o' failed
```

**Comment by Warrows** [comment]
@Fuzzbawls nice catch, I introduced it when fixing @rejectedpromise case. Both should be good now.

**Comment by Fuzzbawls** [comment]
Fixed now. Compiles/syncs.

**Comment by Mrs-X** [comment]
@Fuzzbawls Do you get it to build on High Sierra?
Because here configure still stops with the unsupported SSL error.

**Comment by Warrows** [comment]
@Mrs-X I guess High Sierra is using OpenSSL 1.1. The point of this PR is to allow compilation with it, but it's still potentially dangerous in terms of consensus, hence the unsupported SSL error. You should be able to bypass it by using `--with-unsupported-ssl` with config instead of these flags.
I just pushed 094fa11 to give this information directly when the error happens.

**Comment by Fuzzbawls** [comment]
@Mrs-X I did my testing on Debian Stretch, which uses OpenSSL 1.1 by default.

Also, ACK 094fa11 with the changed error message.

Note: It should be well understood that this PR does **NOT** aim to ensure consensus compatibility with OpenSSL 1.1, just that compiling is possible.

**Comment by Mrs-X** [comment]
@Fuzzbawls Does your remark mean that we will not merge this?

**Comment by Fuzzbawls** [comment]
@Mrs-X not at all. I think this should be merged (hence the ACK), but just wanted to make it clear that this is only a compile-time fix and that OpenSSL 1.1 is still unsupported and largely untested for consensus critical code.

**Comment by Mrs-X** [comment]
Okay, since I successfully tested https://github.com/PIVX-Project/PIVX/commit/094fa11d365ba68a55baf931fb80cd9cc0565209 as well I'll merge...
